/** File FragmentPositions.kt
 *   @Author pierre.antoine - 02/03/2020 - No copyright.
 **/

package com.uldskull.rolegameassistant.fragments.viewPager.adapter

const val BASIC_INFO_FRAGMENT_POSITION = 0
const val BONDS_FRAGMENT_POSITION = 1
const val IDEALS_FRAGMENT_POSITION = 2
const val ABILITIES_FRAGMENT_POSITION = 3
const val DERIVED_VALUES_1_FRAGMENT_POSITION = 4
const val DERIVED_VALUES_2_FRAGMENT_POSITION = 5
const val OCCUPATIONS_FRAGMENT_POSITION = 6
const val OCCUPATION_FRAGMENT_POSITION = 7
const val HOBBIES_FRAGMENT_POSITION = 8
const val HOBBY_FRAGMENT_POSITION = 9

///////////////////////////////////////////////////////////////////////////////////////////////////

const val PICTURE_FRAGMENT_POSITION = 10
const val ABILITIES_RECYCLER_VIEW_FRAGMENT_POSITION = 11
const val BONDS_RECYCLER_VIEW_FRAGMENT_POSITION = 12
const val HOBBIES_SKILLS_RECYCLER_VIEW_FRAGMENT_POSITION = 13
const val HOBBY_SKILLS_RECYCLER_VIEW_FRAGMENT_POSITION = 14
const val IDEAL_RECYCLER_VIEW_FRAGMENT_POSITION = 15
const val JOB_SKILLS_RECYCLER_VIEW_FRAGMENT_POSITION = 16
const val OCCUPATIONS_SKILLS_RECYCLER_VIEW_FRAGMENT_POSITION = 17
const val CHARACTER_SEARCH_FRAGMENT_POSITION = 18
const val NAVIGATION_BAR_FRAGMENT_POSITION = 19
const val BREED_RECYCLER_VIEW_FRAGMENT_POSITION = 20
const val CHARACTERS_RECYCLER_VIEW_FRAGMENT_POSITION = 20

